//libery Tambahan
const fs = require('fs')
const chalk = require('chalk')


//Tambahan 1
global.loli = [
  "https://i.imgur.com/cvqoK7l.jpg",
  "https://i.imgur.com/r1rm2ry.jpg",
  "https://i.imgur.com/8XO7t9a.jpg",
  "https://i.imgur.com/rTLpecf.jpg",
  "https://i.imgur.com/l9of06d.jpg",
  "https://i.imgur.com/GSegIuQ.jpg",
  "https://i.imgur.com/nSwNlyf.jpg",
  "https://i.imgur.com/iWhZIYl.jpg",
  "https://i.imgur.com/53x02Cj.jpg",
  "https://i.imgur.com/kqrgbGx.jpg",
  "https://i.imgur.com/p9rFiqZ.jpg",
  "https://i.imgur.com/Fr1Biar.jpg",
  "https://i.imgur.com/Y0pOrf4.jpg",
  "https://i.imgur.com/DLbggpI.jpg",
  "https://i.imgur.com/wQWKt8t.jpg",
  "https://i.imgur.com/bqm2ror.jpg",
  "https://i.imgur.com/YjdCC5T.jpg",
  "https://i.imgur.com/JIsiLyr.jpg",
  "https://i.imgur.com/smwHPTJ.jpg",
  "https://i.imgur.com/Rj7btya.jpg",
  "https://i.imgur.com/rvbxepM.jpg",
  "https://i.imgur.com/RNU9BjN.jpg",
  "https://i.imgur.com/sXWfHxx.jpg",
  "https://i.imgur.com/4hgUEny.jpg",
  "https://i.imgur.com/rQNFNIR.jpg",
  "https://i.imgur.com/NIkfoSt.jpg",
  "https://i.imgur.com/gXJCV7E.jpg",
  "https://i.imgur.com/i8pWglI.jpg",
  "https://i.imgur.com/pTgKmHa.jpg",
  "https://i.imgur.com/T5QtZ9I.jpg",
  "https://i.imgur.com/gIHmi7S.jpg",
  "https://i.imgur.com/U3MCtzx.jpg",
  "https://i.imgur.com/5hJCG2f.jpg",
  "https://i.imgur.com/OzBgd1W.jpg",
  "https://i.imgur.com/3TvSX1i.jpg",
  "https://i.imgur.com/b2MkoYM.jpg",
  "https://i.imgur.com/Dtru3fp.jpg",
  "https://i.imgur.com/vkqLf9v.jpg",
  "https://i.imgur.com/b1vBRTV.jpg",
  "https://i.imgur.com/eMv5vkT.jpg",
  "https://i.imgur.com/1kbChJv.jpg",
  "https://i.imgur.com/hQFq7aG.jpg",
  "https://i.imgur.com/bWbqyNE.jpg",
  "https://i.imgur.com/fXhu9Yc.jpg",
  "https://i.imgur.com/QutckMk.jpg",
  "https://i.imgur.com/VKrAV4e.jpg",
  "https://i.imgur.com/vzbezXa.jpg",
  "https://i.imgur.com/UTk4A6G.jpg",
  "https://i.imgur.com/SSS7cE4.jpg",
  "https://i.imgur.com/H2WQ3Rs.jpg",
  "https://i.imgur.com/VK8ibDW.jpg",
  "https://i.imgur.com/my9rWpH.jpg",
  "https://i.imgur.com/83UBvmx.jpg",
  "https://i.imgur.com/9J1txSW.jpg",
  "https://i.imgur.com/ZjYQem6.jpg",
  "https://i.imgur.com/tzqq3tg.jpg",
  "https://i.imgur.com/E8gxWdF.jpg",
  "https://i.imgur.com/kN1MpzR.jpg",
  "https://i.imgur.com/s8ql7VD.jpg",
  "https://i.imgur.com/BcjcGwf.jpg",
  "https://i.imgur.com/aFeqLQJ.jpg",
  "https://i.imgur.com/CaUoyOy.jpg",
  "https://i.imgur.com/w5dY397.png",
  "https://i.imgur.com/qouyaqF.png",
  "https://i.imgur.com/pi4zAhE.png",
  "https://i.imgur.com/Sz8gl1s.jpg",
  "https://i.imgur.com/mCcs2NN.jpg",
  "https://i.imgur.com/v3hTo6J.jpg",
  "https://i.imgur.com/57Th63e.jpg",
  "https://i.imgur.com/LpX93lR.jpg",
  "https://i.imgur.com/rNEUT4Z.jpg",
  "https://i.imgur.com/XnDOll0.jpg",
  "https://i.imgur.com/7neOAz7.jpg",
  "https://i.imgur.com/ARiLeyr.jpg",
  "https://i.imgur.com/UaolzDQ.jpg",
  "https://i.imgur.com/whQug6G.jpg",
  "https://i.imgur.com/GZ6WuYd.jpg",
  "https://i.imgur.com/eZrIUVn.jpg",
  "https://i.imgur.com/kMCASul.jpg",
  "https://i.imgur.com/xWyvOfG.jpg",
  "https://i.imgur.com/1PdrS8J.jpg",
  "https://i.imgur.com/FZhF1n7.jpg",
  "https://i.imgur.com/OK36OhR.jpg",
  "https://i.imgur.com/PvrMhRa.jpg",
  "https://i.imgur.com/WAGxTZr.jpg",
  "https://i.imgur.com/EXdzs7O.jpg",
  "https://i.imgur.com/uxHV6lt.jpg",
  "https://i.imgur.com/AyM8Dr9.jpg",
  "https://i.imgur.com/KYDbGQ8.jpg",
  "https://i.imgur.com/J1pVIzq.jpg",
  "https://i.imgur.com/VrvjWS9.jpg",
  "https://i.imgur.com/SCt9NUS.jpg",
  "https://i.imgur.com/hGUv0zE.jpg",
  "https://i.imgur.com/rdCIY2h.jpg",
  "https://i.imgur.com/pVEF4I6.jpg",
  "https://i.imgur.com/cm6q99h.jpg",
  "https://i.imgur.com/jVIThnw.jpg",
  "https://i.imgur.com/dng9fcA.jpg",
  "https://i.imgur.com/cjqGgBS.jpg",
  "https://i.imgur.com/XXaXqxD.jpg",
  "https://i.imgur.com/euxUpho.jpg",
  "https://i.imgur.com/9QySRv8.jpg",
  "https://i.imgur.com/JNa8XUg.jpg",
  "https://i.imgur.com/qYcpJr7.jpg",
  "https://i.imgur.com/2MObaOL.jpg",
  "https://i.imgur.com/Z8I8ppo.jpg",
  "https://i.imgur.com/gKCd4ko.jpg",
  "https://i.imgur.com/0CqXQjO.jpg",
  "https://i.imgur.com/Giuoo8H.jpg",
  "https://i.imgur.com/egKQ6Tw.jpg",
  "https://i.imgur.com/qdYU24C.jpg",
  "https://i.imgur.com/SUGJFWU.jpg",
  "https://i.imgur.com/nHS2Hqn.jpg",
  "https://i.imgur.com/iBkUCqD.jpg",
  "https://i.imgur.com/xW2EIYv.jpg",
  "https://i.imgur.com/KHMeOac.jpg",
  "https://i.imgur.com/PCx0r82.jpg",
  "https://i.imgur.com/CYDgDiT.jpg",
  "https://i.imgur.com/l6OnG4R.jpg",
  "https://i.imgur.com/E1JjyQb.jpg",
  "https://i.imgur.com/8YcibAv.jpg",
  "https://i.imgur.com/khT5P7q.jpg",
  "https://i.imgur.com/Ecpl5ig.jpg",
  "https://i.imgur.com/nFhXDSv.jpg",
  "https://i.imgur.com/jwliTrs.jpg",
  "https://i.imgur.com/IPcxQxr.jpg",
  "https://i.imgur.com/mC7Jwam.jpg",
  "https://i.imgur.com/fXCkoWO.jpg",
  "https://i.imgur.com/Q7PzkLS.jpg",
  "https://i.imgur.com/l6Yv7il.jpg",
  "https://i.imgur.com/sdDMwGz.jpg",
  "https://i.imgur.com/SjhcUYT.jpg",
  "https://i.imgur.com/jO2Ecs2.jpg",
  "https://i.imgur.com/rjYuiVx.jpg",
  "https://i.imgur.com/0jiYDHI.jpg",
  "https://i.imgur.com/CT1MDI3.jpg",
  "https://i.imgur.com/qxyIKQr.jpg",
  "https://i.imgur.com/uDQjHRP.jpg",
  "https://i.imgur.com/ol2Oj8R.jpg",
  "https://i.imgur.com/Wfjb2Ai.jpg",
  "https://i.imgur.com/74y3fAJ.jpg",
  "https://i.imgur.com/dDjh4Uw.jpg",
  "https://i.imgur.com/CjpjWxM.jpg",
  "https://i.imgur.com/NIC81ns.jpg",
  "https://i.imgur.com/0KkbJge.jpg",
  "https://i.imgur.com/xqBJ4tV.jpg",
  "https://i.imgur.com/1zHEb7K.jpg",
  "https://i.imgur.com/TOFZzI1.jpg",
  "https://i.imgur.com/1e11CSw.jpg",
  "https://i.imgur.com/IccBn2c.jpg",
  "https://i.imgur.com/XRZGGcJ.jpg",
  "https://i.imgur.com/PFtdlMw.jpg",
  "https://i.imgur.com/f3drZoc.jpg",
  "https://i.imgur.com/352upti.jpg",
  "https://i.imgur.com/c1uJml9.jpg",
  "https://i.imgur.com/Vi5s22D.jpg",
  "https://i.imgur.com/aQqsIEE.jpg",
  "https://i.imgur.com/irpCe7P.jpg",
  "https://i.imgur.com/Zx6Yjff.jpg",
  "https://i.imgur.com/LgKKZ4R.jpg",
  "https://i.imgur.com/FCGTCXZ.jpg",
  "https://i.imgur.com/f1u6YTD.png",
  "https://i.imgur.com/6O1vzmr.jpg",
  "https://i.imgur.com/L5H3zRz.png",
  "https://i.imgur.com/LFC8bNW.jpg",
  "https://i.imgur.com/zvEYbeN.jpg",
  "https://i.imgur.com/gACJQoI.jpg",
  "https://i.imgur.com/7iXAyWx.jpg",
  "https://i.imgur.com/xM3grxy.jpg",
  "https://i.imgur.com/IoWiIW3.jpg",
  "https://i.imgur.com/o9AjYD4.jpg",
  "https://i.imgur.com/8C4hJNm.png",
  "https://i.imgur.com/EzbwAlV.jpg",
  "https://i.imgur.com/579AXWF.jpg",
  "https://i.imgur.com/5JWh0g2.jpg",
  "https://i.imgur.com/2J0ZLVw.jpg",
  "https://i.imgur.com/gAX2K9U.jpg",
  "https://i.imgur.com/rf4BQTk.jpg",
  "https://i.imgur.com/JXeXDJY.jpg",
  "https://i.imgur.com/QbcSeQd.jpg",
  "https://i.imgur.com/xgy2bEF.jpg",
  "https://i.imgur.com/MpKbH1S.jpg",
  "https://i.imgur.com/b3B3TRg.jpg",
  "https://i.imgur.com/0SjdKRJ.jpg",
  "https://i.imgur.com/WxJ4Dty.jpg",
  "https://i.imgur.com/yhYvKdi.jpg",
  "https://i.imgur.com/07Cq8eX.jpg",
  "https://i.imgur.com/uT7p0IQ.jpg",
  "https://i.imgur.com/yjrxPh1.jpg",
  "https://i.imgur.com/CJTkcpu.jpg",
  "https://i.imgur.com/ngtHTXw.jpg",
  "https://i.imgur.com/iGoSGYS.jpg",
  "https://i.imgur.com/6wZtAFN.jpg",
  "https://i.imgur.com/fZ9nAIm.jpg",
  "https://i.imgur.com/S5f4IgT.jpg",
  "https://i.imgur.com/IBlQ7td.jpg",
  "https://i.imgur.com/BzZyyj6.jpg",
  "https://i.imgur.com/X8FBjTy.jpg",
  "https://i.imgur.com/MUBx7Fv.jpg",
  "https://i.imgur.com/hKquzgo.jpg",
  "https://i.imgur.com/GPSI7tl.jpg",
  "https://i.imgur.com/hXXe9uI.jpg",
  "https://i.imgur.com/varo8zI.jpg",
  "https://i.imgur.com/SJ2tSzt.jpg",
  "https://i.imgur.com/Zn61xQ3.jpg",
  "https://i.imgur.com/IH4Cc82.jpg",
  "https://i.imgur.com/7VuDuEX.jpg",
  "https://i.imgur.com/iO8e46Y.jpg",
  "https://i.imgur.com/d1yPdFW.jpg",
  "https://i.imgur.com/Ny2USkc.jpg",
  "https://i.imgur.com/X6OpdJn.jpg",
  "https://i.imgur.com/A8I2ZTy.jpg",
  "https://i.imgur.com/FHwGc6j.jpg",
  "https://i.imgur.com/3oxBfue.jpg",
  "https://i.imgur.com/s0cb0wy.jpg",
  "https://i.imgur.com/xJRBUyS.jpg",
  "https://i.imgur.com/pMrRebM.jpg",
  "https://i.imgur.com/eRagL8l.jpg",
  "https://i.imgur.com/jv7FQyz.jpg",
  "https://i.imgur.com/lk8eH5C.jpg",
  "https://i.imgur.com/pBVU4oI.jpg",
  "https://i.imgur.com/sgXgSyZ.jpg",
  "https://i.imgur.com/uriQw5p.jpg",
  "https://i.imgur.com/mHCGMvd.jpg",
  "https://i.imgur.com/Jswt4WI.jpg",
  "https://i.imgur.com/7FrFFmk.jpg",
  "https://i.imgur.com/mj54g94.jpg",
  "https://i.imgur.com/GbdRNHn.jpg",
  "https://i.imgur.com/IdBY0RC.jpg",
  "https://i.imgur.com/jt9g4qv.jpg",
  "https://i.imgur.com/cYLW6ND.jpg",
  "https://i.imgur.com/a6bG9OJ.jpg",
  "https://i.imgur.com/Vp4CrzA.jpg",
  "https://i.imgur.com/bJosWlx.jpg",
  "https://i.imgur.com/q04kkvk.jpg",
  "https://i.imgur.com/dDeGegy.jpg",
  "https://i.imgur.com/PsGH4iF.jpg",
  "https://i.imgur.com/XzNwtKs.png",
  "https://i.imgur.com/G76GnQs.jpg",
  "https://i.imgur.com/9Pop0jk.jpg",
  "https://i.imgur.com/EvPbdLv.jpg",
  "https://i.imgur.com/yMV4Euc.jpg",
  "https://i.imgur.com/EG519Cl.jpg",
  "https://i.imgur.com/H8bquFj.jpg",
  "https://i.imgur.com/8VlMtwn.jpg",
  "https://i.imgur.com/XcavaOU.jpg",
  "https://i.imgur.com/rIaXF4X.jpg",
  "https://i.imgur.com/POQtJbb.jpg",
  "https://i.imgur.com/AOJGdKS.jpg",
  "https://i.imgur.com/RBVnaaY.jpg",
  "https://i.imgur.com/8i848vt.jpg",
  "https://i.imgur.com/CMkZ0sG.jpg",
  "https://i.imgur.com/405HlDU.jpg",
  "https://i.imgur.com/yqfaXY6.jpg",
  "https://i.imgur.com/5rNqyY7.jpg",
  "https://i.imgur.com/RKkCq8P.jpg",
  "https://i.imgur.com/vhWaESf.jpg",
  "https://i.imgur.com/mvs9JHj.jpg",
  "https://i.imgur.com/Du7uY2o.jpg",
  "https://i.imgur.com/vsmmU9M.jpg",
  "https://i.imgur.com/h85RIBK.jpg",
  "https://i.imgur.com/yBXlOHY.jpg",
  "https://i.imgur.com/3NMCJZv.jpg",
  "https://i.imgur.com/1dz7k1S.jpg",
  "https://i.imgur.com/hZFrdFW.jpg",
  "https://i.imgur.com/8aeoeYN.jpg",
  "https://i.imgur.com/XFKDEIJ.jpg",
  "https://i.imgur.com/Gv3VTue.jpg",
  "https://i.imgur.com/NluTBYi.jpg",
  "https://i.imgur.com/9xIZshz.jpg",
  "https://i.imgur.com/sORiJ4l.jpg",
  "https://i.imgur.com/7HEjmnF.jpg",
  "https://i.imgur.com/kqwpjvM.jpg",
  "https://i.imgur.com/G4CWkdA.jpg",
  "https://i.imgur.com/zljM2wk.jpg",
  "https://i.imgur.com/MIoFqaW.jpg",
  "https://i.imgur.com/VTzw4ZG.jpg",
  "https://i.imgur.com/i9erTFD.jpg",
  "https://i.imgur.com/A1arIN6.jpg",
  "https://i.imgur.com/4csKEij.jpg",
  "https://i.imgur.com/4ytTvdj.jpg",
  "https://i.imgur.com/lMTwpnQ.jpg",
  "https://i.imgur.com/dvMzGCc.jpg",
  "https://i.imgur.com/UplQQ8U.jpg",
  "https://i.imgur.com/LSddlbB.jpg",
  "https://i.imgur.com/PUOkYZp.jpg",
  "https://i.imgur.com/KSgP3or.jpg",
  "https://i.imgur.com/pPZlMYE.jpg",
  "https://i.imgur.com/Q3pB3JT.jpg",
  "https://i.imgur.com/EMe85w7.jpg",
  "https://i.imgur.com/1dhFaiz.jpg",
  "https://i.imgur.com/tyG2tLv.jpg",
  "https://i.imgur.com/DqK8zjX.jpg",
  "https://i.imgur.com/iLBiiLo.jpg",
  "https://i.imgur.com/pegvicI.jpg",
  "https://i.imgur.com/ViJOBaQ.jpg",
  "https://i.imgur.com/N74QlWf.jpg",
  "https://i.imgur.com/17PCCM1.jpg",
  "https://i.imgur.com/PINdg09.jpg",
  "https://i.imgur.com/3j7ltKs.jpg",
  "https://i.imgur.com/bfoaURB.jpg",
  "https://i.imgur.com/FZbfA68.jpg",
  "https://i.imgur.com/YkTyXp0.jpg",
  "https://i.imgur.com/DqF8cRf.jpg",
  "https://i.imgur.com/lz7rlYb.jpg",
  "https://i.imgur.com/qafsgIF.jpg",
  "https://i.imgur.com/56XrZUq.jpg",
  "https://i.imgur.com/rCpKDgd.jpg",
  "https://i.imgur.com/HOsFONj.jpg",
  "https://i.imgur.com/edDPEvs.jpg",
  "https://i.imgur.com/wYuIGVH.png",
  "https://i.imgur.com/LSbd9Wj.jpg",
  "https://i.imgur.com/KwgVsYF.jpg",
  "https://i.imgur.com/Eujsxkf.jpg",
  "https://i.imgur.com/LVmj61N.jpg",
  "https://i.imgur.com/hfGo3OS.jpg",
  "https://i.imgur.com/BEMHZ2j.jpg",
  "https://i.imgur.com/1D8jSsK.jpg",
  "https://i.imgur.com/T7QW4Ih.jpg",
  "https://i.imgur.com/z1Mm4nQ.jpg",
  "https://i.imgur.com/ezxEDso.jpg",
  "https://i.imgur.com/8uMwsX8.jpg",
  "https://i.imgur.com/pkoItBN.jpg",
  "https://i.imgur.com/2sQWuQb.jpg",
  "https://i.imgur.com/A502SkB.jpg",
  "https://i.imgur.com/abXCscs.jpg",
  "https://i.imgur.com/1c1oc7r.jpg",
  "https://i.imgur.com/NDQskOe.jpg",
  "https://i.imgur.com/MlFrAcW.png",
  "https://i.imgur.com/CnNE9TU.jpg",
  "https://i.imgur.com/E4EJ8OO.jpg",
  "https://i.imgur.com/NPcKWaQ.jpg",
  "https://i.imgur.com/yyuaxE0.jpg",
  "https://i.imgur.com/zKa4tlb.jpg",
  "https://i.imgur.com/bNOvXDM.jpg",
  "https://i.imgur.com/GKMG3wx.jpg",
  "https://i.imgur.com/oV7RntX.jpg",
  "https://i.imgur.com/Q93S52s.jpg",
  "https://i.imgur.com/2k5BlPs.jpg",
  "https://i.imgur.com/nOaSeBy.jpg",
  "https://i.imgur.com/KKilV96.png",
  "https://i.imgur.com/rB65Ogl.jpg",
  "https://i.imgur.com/QBVOim0.jpg",
  "https://i.imgur.com/FPdNAfX.jpg",
  "https://i.imgur.com/PlWhg77.jpg",
  "https://i.imgur.com/wSoVoiq.jpg",
  "https://i.imgur.com/2lINUF6.png",
  "https://i.imgur.com/mFV54d5.jpg",
  "https://i.imgur.com/miVWDFs.jpg",
  "https://i.imgur.com/5AQo1EV.jpg",
  "https://i.imgur.com/cIbfUOw.jpg",
  "https://i.imgur.com/jUH2dFn.jpg"
]
global.cosplay = [
"https://i.ibb.co/WD3ZK2K/main-qimg-4bce93181d6bc8e544036cda41e70291-lq.jpg",
"https://i.ibb.co/NZ6Lfyd/6a60fcb180b9b7f18e23724c66f043b6.jpg",
"https://i.ibb.co/JjvM45P/animesher-com-tenten-ino-cosplayers-cute-cosplay-girls-best-anime-cosplay-1176896.jpg",
"https://i.ibb.co/yNrRrP1/886000bd60ebcdee06845aa2af8f07ee.jpg",
"https://i.ibb.co/MSHTvbS/e5f286ded660f38e8f4db73c8dfafba8.jpg",
"https://i.ibb.co/0JcZ8mh/8f93b9d3f67264f8a8a46f33d9bd1cc6.jpg",
"https://i.ibb.co/grygDDx/744d6ae02467fff7dd3a3d026dc1ae4f.jpg",
"https://i.ibb.co/z2jYxq7/FTFou-FUUUAAb9k-V.jpg",
"https://i.ibb.co/nMmkB1y/x279605-jpg-pagespeed-ic-PEc-Mo-Faq0m.jpg",
"https://i.ibb.co/5GtHGtH/45c33cfbb9c2cf44d18c43335e9d240e.jpg",
"https://i.ibb.co/qBfCjLb/1625759106-34-Anime-Naruto-Character-Tarumi-Mei-Cn-senyamiku.jpg",
"https://i.ibb.co/vXPKRQL/top-cosplayer-enako-nailed-the-90.jpg",
"https://i.ibb.co/NSBfwjj/av5-MOVZ-700b.jpg",
"https://i.ibb.co/0MWj850/350cb91f3a7498de8d4ea0297dcb28be.jpg",
"https://i.ibb.co/swqh54v/5fa786f41f042a9eee0c937e-Senya-Miku-3.jpg",
"https://i.ibb.co/Q87p21y/58064-56582-4627.jpg",
"https://i.ibb.co/SR9xrqc/9eb7b9b8d3b7fbaa0b6030de4159e425.jpg",
"https://i.ibb.co/cDKyJSc/Dinb-XAa-U8-AAo7-Db.jpg",
"https://i.ibb.co/Y832qKP/d2d26333a1e3dc6d6c616a5b3d8fd105.jpg",
"https://i.ibb.co/0BxmfLp/15d120fd8d65d19a50266981d6e0978a.jpg",
"https://i.ibb.co/myvn4Z6/e8282c7fac9f6548a7429695af1b0c61.jpg",
"https://i.ibb.co/LvtZT81/9fcac149fe0965cdc158888ffbf8350b.jpg",
"https://i.ibb.co/Wn9NjJN/70aca088d3e16b644ee70afcd2ff9e99.jpg",
"https://i.ibb.co/9V7v6Ly/8364cf41efc8fc99a2b5eea1ab70cb56.jpg",
"https://i.ibb.co/b3HvCRq/63ebe41d3835a4e693f2fdab70c31076.jpg",
"https://i.ibb.co/q9xVPsn/cc5ef38752f5c608353751717ff8395f.jpg",
"https://i.ibb.co/RcL6NG5/c4427cde8ae04a6f4d45a64e3a2f97e9.jpg",
"https://i.ibb.co/FKRns41/b4fd3a56696450ba5b7b7d7f7f2a7414.png",
"https://i.ibb.co/Y7RJYbM/1a2865ae26d70b6a477c8311d43c735b.jpg",
"https://i.ibb.co/DM2ydxq/6098dae77714a052109ae5822c219885.jpg",
"https://i.ibb.co/47FM8bP/42736e56ddfe7c399a7bd45e04ee4f27.jpg",
"https://i.ibb.co/27dYbZ5/3a3efc8f03eb6122b0e04841f4177c2c.jpg",
"https://i.ibb.co/bFs7v2F/10c96a967c607b49f24d239bdb21d162.jpg",
"https://i.ibb.co/7RJwDzb/animesher-com-anna-cosplay-k-cosplay-cute-anime-girl-635889.jpg",
"https://i.ibb.co/nj9ndmp/25bed47c9e4e198a6a577946559a93be.jpg",
"https://i.ibb.co/1K6T6mj/a00e570f19b591a63a0b51a7f9b698b8.jpg",
"https://i.ibb.co/rMJ1qJw/Anime-Cosplay-Working-Cell-Platelets-Cosplay-Cute-Costume-Halloween-Haikyuu-Japanese-Cos-Women-Top-s.jpg",
"https://i.ibb.co/f9j8f40/e396a7e586e845348b2baa540705c7dd.jpg",
"https://i.ibb.co/0yQ5DGb/7fa9ed3e213db5dae77d0bb8aee53cd8.jpg",
"https://i.ibb.co/q5VPN3Z/de1ce301f927c0568343095c93415e45.jpg",
"https://i.ibb.co/gWZX0sx/ef6c48d482734b8a8e3f935c7f49a408.jpg",
"https://i.ibb.co/BKHg6Hv/ba82f7794da9216d20164c944831f80e.jpg",
"https://i.ibb.co/F4FgMpF/soul-land-xiaowu-cosplay-1639628587-112001ed.jpg",
"https://i.ibb.co/VTXsZvT/30839424e3b601edc0f8dcf4b533a51e.jpg",
"https://i.ibb.co/DDmX9RC/3794fe189d0b5193c39b5c1bc9df907d.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0040.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0058.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0048.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0059.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0047.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0050.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0053.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0041.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0052.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0057.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0045.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0056.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0044.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0051.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0046.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0055.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0043.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0054.jpg",
"https://www.linkpicture.com/q/IMG-20220710-WA0042.jpg"
]
global.motivasi = [
"Jangan bicara, bertindak saja. Jangan katakan, tunjukkan saja. Jangan janji, buktikan saja.",
"Jangan pernah berhenti melakukan yang terbaik hanya karena seseorang tidak memberi Anda penghargaan.",
"Bekerja saat mereka tidur. Belajar saat mereka berpesta. Hemat sementara mereka menghabiskan. Hiduplah seperti mimpi mereka.",
"Kunci sukses adalah memusatkan pikiran sadar kita pada hal-hal yang kita inginkan, bukan hal-hal yang kita takuti.",
"Jangan takut gagal. Ketakutan berada di tempat yang sama tahun depan seperti Anda saat ini.",
"Jika kita terus melakukan apa yang kita lakukan, kita akan terus mendapatkan apa yang kita dapatkan.",
"Jika Anda tidak dapat mengatasi stres, Anda tidak akan mengelola kesuksesan.",
"Bersikap keras kepala tentang tujuan Anda dan fleksibel tentang metode Anda.",
"Kerja keras mengalahkan bakat ketika bakat tidak bekerja keras.",
"Ingatlah bahwa pelajaran terbesar dalam hidup biasanya dipelajari dari saat-saat terburuk dan dari kesalahan terburuk.",
"Hidup bukan tentang menunggu badai berlalu, tetapi belajar menari di tengah hujan.",
"Jika rencananya tidak berhasil, ubah rencananya bukan tujuannya.",
"Jangan takut kalau hidupmu akan berakhir; takutlah kalau hidupmu tak pernah dimulai.",
"Orang yang benar-benar hebat adalah orang yang membuat setiap orang merasa hebat.",
"Pengalaman adalah guru yang berat karena dia memberikan tes terlebih dahulu, kemudian pelajarannya.",
"Mengetahui seberapa banyak yang perlu diketahui adalah awal dari belajar untuk hidup.",
"Sukses bukanlah akhir, kegagalan tidak fatal. Yang terpenting adalah keberanian untuk melanjutkan.",
"Lebih baik gagal dalam orisinalitas daripada berhasil meniru.",
"Berani bermimpi, tapi yang lebih penting, berani melakukan tindakan di balik impianmu.",
"Tetapkan tujuan Anda tinggi-tinggi, dan jangan berhenti sampai Anda mencapainya.",
"Kembangkan kesuksesan dari kegagalan. Keputusasaan dan kegagalan adalah dua batu loncatan paling pasti menuju sukses.",
"Jenius adalah satu persen inspirasi dan sembilan puluh sembilan persen keringat.",
"Sukses adalah tempat persiapan dan kesempatan bertemu.",
"Ketekunan gagal 19 kali dan berhasil pada kesempatam yang ke-20.",
"Jalan menuju sukses dan jalan menuju kegagalan hampir persis sama.",
"Sukses biasanya datang kepada mereka yang terlalu sibuk mencarinya.",
"Jangan tunda pekerjaanmu sampai besok, sementara kau bisa mengerjakannya hari ini.",
"20 tahun dari sekarang, kau mungkin lebih kecewa dengan hal-hal yang tidak sempat kau lakukan alih-alih yang sudah.",
"Jangan habiskan waktumu memukuli tembok dan berharap bisa mengubahnya menjadi pintu.",
"Kesempatan itu mirip seperti matahari terbit. Kalau kau menunggu terlalu lama, kau bisa melewatkannya.",
"Hidup ini terdiri dari 10 persen apa yang terjadi padamu dan 90 persen bagaimana caramu menyikapinya.",
"Ada tiga cara untuk mencapai kesuksesan tertinggi: Cara pertama adalah bersikap baik. Cara kedua adalah bersikap baik. Cara ketiga adalah menjadi baik.",
"Alasan nomor satu orang gagal dalam hidup adalah karena mereka mendengarkan teman, keluarga, dan tetangga mereka.",
"Waktu lebih berharga daripada uang. Kamu bisa mendapatkan lebih banyak uang, tetapi kamu tidak bisa mendapatkan lebih banyak waktu.",
"Penetapan tujuan adalah rahasia masa depan yang menarik.",
"Saat kita berusaha untuk menjadi lebih baik dari kita, segala sesuatu di sekitar kita juga menjadi lebih baik.",
"Pertumbuhan dimulai ketika kita mulai menerima kelemahan kita sendiri.",
"Janganlah pernah menyerah ketika Anda masih mampu berusaha lagi. Tidak ada kata berakhir sampai Anda berhenti mencoba.",
"Kemauan adalah kunci sukses. Orang-orang sukses, berusaha keras apa pun yang mereka rasakan dengan menerapkan keinginan mereka untuk mengatasi sikap apatis, keraguan atau ketakutan.",
"Janganlah pernah menyerah ketika Anda masih mampu berusaha lagi. Tidak ada kata berakhir sampai Anda berhenti mencoba.",
"Kemauan adalah kunci sukses. Orang-orang sukses, berusaha keras apa pun yang mereka rasakan dengan menerapkan keinginan mereka untuk mengatasi sikap apatis, keraguan atau ketakutan.",
"Hal pertama yang dilakukan orang sukses adalah memandang kegagalan sebagai sinyal positif untuk sukses.",
"Ciri khas orang sukses adalah mereka selalu berusaha keras untuk mempelajari hal-hal baru.",
"Sukses adalah mendapatkan apa yang kamu inginkan, kebahagiaan menginginkan apa yang kamu dapatkan.",
"Orang pesimis melihat kesulitan di setiap kesempatan. Orang yang optimis melihat peluang dalam setiap kesulitan.",
"Keraguan membunuh lebih banyak mimpi daripada kegagalan.",
"Lakukan apa yang harus kamu lakukan sampai kamu dapat melakukan apa yang ingin kamu lakukan.",
"Optimistis adalah salah satu kualitas yang lebih terkait dengan kesuksesan dan kebahagiaan daripada yang lain.",
"Penghargaan paling tinggi bagi seorang pekerja keras bukanlah apa yang dia peroleh dari pekerjaan itu, tapi seberapa berkembang ia dengan kerja kerasnya itu.",
"Cara terbaik untuk memulai adalah dengan berhenti berbicara dan mulai melakukan.",
"Kegagalan tidak akan pernah menyusul jika tekad untuk sukses cukup kuat.",
"Cinta tak bisa tiba-tiba ada, seperti sebuah batu. Ia harus dibuat. Layaknya sebuah roti: akan selalu dibuat ulang untuk menghasilkan yang baru. - Ursula K. Le Guin"
]



//Dibawah Ini Jangan Di rubah Biar tidak error
let file = require.resolve(__filename)
fs.watchFile(file, () => {
	fs.unwatchFile(file)
	console.log(chalk.redBright(`Update'${__filename}'`))
	delete require.cache[file]
	require(file)
})
